# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
# Unable to inspect table 'accounts_forgot'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'auth_group'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'auth_group_permissions'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'auth_permission'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'auth_user'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'auth_user_groups'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'auth_user_user_permissions'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'django_admin_log'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'django_content_type'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'django_migrations'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'django_session'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_accept'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_activegroup'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_associatedegreefile'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_associatedegreefilename'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_budget'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_businessblog'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_businessblog_parametre'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_businessblogparametretype'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_calendar'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_calendarname'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_calendaryeka'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_categoryitem'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_city'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_claim'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_collateral'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_communication'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_company'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_company_companyuser'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_company_files'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_companyfilenames'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_companyfiles'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_companyuser'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_competition'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_competition_company'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_competitionapplication'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_competitionapplication_necessary'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_competitioncompany'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_connectionregion'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_connectionregion_cities'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_connectionregion_yekacompetition'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_connectionunit'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_consortiumcompany'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_coordinate'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_country'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_directorycommission'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_directorymember'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_directorymemberrole'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_district'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_employee'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_employment'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_eskalasyon'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_extratime'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_extratimefile'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_factory'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_factory_file'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_factoryfile'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_factoryfilename'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_file'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_fileextension'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_helpmenu'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_historygroup'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_institution'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_location'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_logs'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_menu'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_neighborhood'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_newspaper'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_notification'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_notificationuser'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_permission'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_permissiongroup'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_person'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_produceamount'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_progressreport'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_proposal'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_proposal_coordinate'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_proposal_institution'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_proposal_location'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_proposalactive'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_proposalinstitution'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_proposalsubyeka'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_settings'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_vacationday'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yeka'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yeka_connection_region'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaaccept'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaaccept_accept'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaapplicationfile'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaapplicationfilename'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaassociatedegree'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaassociatedegree_associatedegree'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekabudget'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekabudget_budget'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekabusiness'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekabusiness_businessblogs'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekabusinessblog'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekabusinessblog_companies'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekabusinessblog_parameter'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekabusinessblogparemetre'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompany'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompany_files'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompanyhistory'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompanyuser'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompanyuser_companyuser'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompetition'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompetition_city'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompetitioneskalasyon'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompetitioneskalasyon_eskalasyon'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompetitionperson'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacompetitionpersonhistory'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaconnectionregion'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekacontract'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaemployment'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaemployment_employment'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekafactory'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekafactory_factory'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaguarantee'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaguarantee_guarantee'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaholdingcompetition'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaperson'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekapersonhistory'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaproduceamount'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaproduceamount_amount'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaprogressreport'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaprogressreport_progressreport'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaproposal'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekaproposal_proposal'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekapurchaseguarantee'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'sbs_yekauser'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_admin'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_auto_login'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_adminauth'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_athlete_coach_append'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_auth'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_branches'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_branches_sub'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_city'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_coaches'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_commonuser'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_competition'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_ebysmodule'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_educationseminar'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_ekipman'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_event_application'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_event_join'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_event_officer'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_ffsalon_etap'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_general_file'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_hedef_etap'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_hedef_sampiyona'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_hedef_sampiyona_kulup'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_imac_etap'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_kura'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_kura_sonuclari'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_login_pc'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_loginauth'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_member_log'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_membership_athlete'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_membership_club'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_membership_coach'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_membership_flightscholl'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_membership_organizer'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_membership_referee'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_mesafe_score'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_milli_sporcu'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_passwordauth'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_personal'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_personal_category'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_puan_durumu_ffsalon'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_puan_durumu_hedef'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_puan_durumu_imac'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_referee_statu'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_smsemail_auth'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_smslist'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_smslist_category'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_smssend_log'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_tezcan'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_tezcan_arakayit'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_tezcan_record'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_ebys_user'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_gecici_kulub_sporcu'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_loginredirect'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_modulemap'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_admin'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_city'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_club'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_equipment'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_event'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_jandarma'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_pilot'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_preregistration'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_signupauth'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_takeoff'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_uts_user'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_branches'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_duyurular'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_egitimmerkezleri'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_epostakayit'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_faaliyettakvimi'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_iltemsilcileri'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_kurumsal'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_language'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_pressrelease'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_slider'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_socialmedia'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_talimatlar'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_versionmanagement'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_video'
# The error was: 'Cursor' object has no attribute 'not_description'
# Unable to inspect table 'system_wiys_yonetimkurulu'
# The error was: 'Cursor' object has no attribute 'not_description'
