from .ekabis.ActiveGroup import ActiveGroup
from .ekabis.CategoryItem import CategoryItem
from .ekabis.City import City
from .ekabis.Claim import Claim
from .ekabis.Communication import Communication
from .ekabis.ActiveGroup import ActiveGroup
from .ekabis.Company import Company
from .ekabis.Country import Country
from sbs.models.tvfbf.DirectoryMemberRole import DirectoryMemberRole
from .ekabis.Employee import Employee
from .ekabis.EnumFields import EnumFields
from .ekabis.Logs import Logs
from .ekabis.Menu import Menu
from .ekabis.Notification import Notification
from .ekabis.Person import Person
from .ekabis.PermissionGroup import PermissionGroup
from .ekabis.Permission import Permission
from .ekabis.ConnectionUnit import ConnectionUnit
from .ekabis.ConnectionRegion import ConnectionRegion
from .ekabis.YekaCompetition import YekaCompetition
from .ekabis.Yeka import Yeka
from .ekabis.YekaPerson import YekaPerson
from .ekabis.YekaConnectionRegion import YekaConnectionRegion
from .ekabis.HistoryGroup import HistoryGroup
from .ekabis.CompanyFileNames import CompanyFileNames
from .ekabis.CompanyUser import CompanyUser
from .ekabis.CompanyFiles import CompanyFiles
from .ekabis.YekaPerson import YekaPerson
from .ekabis.YekaPersonHistory import YekaPersonHistory
from .ekabis.YekaCompany import YekaCompany
from .ekabis.YekaCompanyHistory import YekaCompanyHistory
from .ekabis.YekaBussiness import YekaBusiness
from .ekabis.YekaBusinessBlog import YekaBusinessBlog
from .ekabis.YekaBusinessBlogParemetre import YekaBusinessBlogParemetre
from .ekabis.BusinessBlog import BusinessBlog
from .ekabis.BusinessBlogParametreType import BusinessBlogParametreType
from .ekabis.Calendar import Calendar
from .ekabis.CalendarName import CalendarName
from .ekabis.ExtraTime import ExtraTime
from .ekabis.ConsortiumCompany import ConsortiumCompany
from .ekabis.HelpMenu import HelpMenu
from .ekabis.Accept import Accept
from .ekabis.YekaAccept import YekaAccept
from .ekabis.FactoryFile import FactoryFile
from .ekabis.Neighborhood import Neighborhood
from .ekabis.AssociateDegreeFileName import AssociateDegreeFileName
from .ekabis.NotificationUser import NotificationUser
from .ekabis.YekaPurchaseGuarantee import YekaPurchaseGuarantee
from .ekabis.YekaProduceAmount import YekaProduceAmount
from .ekabis.ProduceAmount import ProduceAmount
from .ekabis.ProposalSubYeka import ProposalSubYeka
from .ekabis.Eskalasyon import Eskalasyon
from .ekabis.YekaCompetitionEskalasyon import YekaCompetitionEskalasyon
from .ekabis.FileExtension import FileExtension
from .ekabis.ReportObject import ReportObject
from .ekabis.YekaCompetitionEskalasyon_eskalasyon import YekaCompetitionEskalasyon_eskalasyon
from .ekabis.YekaHoldingCompetition import YekaHoldingCompetition
from .ekabis.Collateral import Collateral
from .ekabis.YekaGuarantee import YekaGuarantee
from .ekabis.Budget import Budget
from .ekabis.Employment import Employment
from .ekabis.YekaBudget import YekaBudget
from .ekabis.YekaEmployment import YekaEmployment
from .ekabis.CalendarYeka import CalendarYeka
from .ekabis.ProgressReport import ProgressReport
from .ekabis.YekaProgressReport import YekaProgressReport


#HAVASPOR İMPORT

from .tvfbf.Branch import Branch
from .tvfbf.ClubRole import ClubRole
from .tvfbf.Club import Club
from .tvfbf.SportClubUser import SportClubUser
from .tvfbf.Coach import Coach
from .tvfbf.CertificateDegree import CertificateDegree
from .tvfbf.License import License
from .tvfbf.Referee import Referee
from .tvfbf.Organizer import Organizer
from .tvfbf.AirSportsCompetition import AirSportsCompetition
from .tvfbf.EducationSeminar import EducationSeminar
from .tvfbf.HavaLevel import HavaLevel
