# Generated by Django 3.2.6 on 2022-03-09 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, to='sbs.Branch'),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('companyName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Ünvanı')),
                ('companyRepresentative', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Yetkilisi')),
                ('companyTaxOffice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Vergi Dairesi')),
                ('companyTaxNumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Vergi Numarası')),
                ('companyPhoneNumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Telefon Numarası')),
                ('companyEmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Firma E-posta')),
                ('companyAddress', models.TextField(blank=True, null=True, verbose_name='Firma Adresi')),
                ('infoLevel', models.BooleanField(blank=True, default=True, null=True)),
                ('infoStatus', models.BooleanField(blank=True, default=True, null=True)),
                ('branch', models.ManyToManyField(to='sbs.Branch')),
                ('communication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.communication')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('secretId', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Etkinlik Başlığı')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Etkinlik Başlangıç Tarihi')),
                ('finishDate', models.DateField(blank=True, null=True, verbose_name='Etkinlik Bitiş Tarihi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Etkinlik Açıklama')),
                ('createdDate', models.DateTimeField(blank=True, null=True, verbose_name='Etkinlik Oluşturulma Tarihi')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('educationTime', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eğitim Süresi')),
                ('branch', models.ManyToManyField(to='sbs.Branch')),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.city', verbose_name='İl')),
                ('coaches', models.ManyToManyField(to='sbs.Coach')),
                ('creator', models.ForeignKey(blank=True, db_column='auth_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Etkinliği Oluşturan Kişi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirSportsCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('secretId', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Etkinlik Başlığı')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Etkinlik Başlangıç Tarihi')),
                ('finishDate', models.DateField(blank=True, null=True, verbose_name='Etkinlik Bitiş Tarihi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Etkinlik Açıklama')),
                ('createdDate', models.DateTimeField(blank=True, null=True, verbose_name='Etkinlik Oluşturulma Tarihi')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('branch', models.ManyToManyField(to='sbs.Branch')),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.city', verbose_name='İl')),
                ('creator', models.ForeignKey(blank=True, db_column='auth_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Etkinliği Oluşturan Kişi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
