# Generated by Django 3.2.6 on 2022-03-11 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbs', '0002_auto_20220309_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='HavaLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('levelType', models.CharField(choices=[('VISA', 'VISA'), ('GRADE', 'GRADE'), ('BELT', 'BELT')], max_length=128, verbose_name='Leveller')),
                ('isActive', models.BooleanField(default=False)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('expireDate', models.DateField(blank=True, null=True)),
                ('durationDay', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'), ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Onay Durumu')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='dekont/', verbose_name='Belge ')),
                ('form', models.FileField(upload_to='form/', verbose_name='Form ')),
                ('secretId', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.branch')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.city', verbose_name='İl')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='referee',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='status',
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.branch'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.categoryitem'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='cezaYazisi',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='referee/', verbose_name='Ceza Yazısı'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='diploma',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='referee/', verbose_name='Diploma'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='hakemBilgiFormu',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='referee/', verbose_name='Hakem Bilgi Formu'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='nufusCuzdani',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='referee/', verbose_name='Nufüs Cüzdanı'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='sabikaKaydi',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='referee/', verbose_name='Sabıka Kaydı'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='saglikBeyanFormu',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='referee/', verbose_name='Sağlık Beyan Formu'),
        ),
        migrations.DeleteModel(
            name='RefereeStatus',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='havalevel',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.categoryitem'),
        ),
        migrations.AddField(
            model_name='havalevel',
            name='definitionChangeUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referee',
            name='grades',
            field=models.ManyToManyField(related_name='Judgegrades', to='sbs.HavaLevel'),
        ),
        migrations.AddField(
            model_name='referee',
            name='visa',
            field=models.ManyToManyField(related_name='Judgevisa', to='sbs.HavaLevel'),
        ),
    ]
