# Generated by Django 3.2.6 on 2022-03-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0003_auto_20220311_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='grades',
            field=models.ManyToManyField(related_name='CoachGrades', to='sbs.HavaLevel'),
        ),
        migrations.AddField(
            model_name='coach',
            name='visa',
            field=models.ManyToManyField(related_name='CoachVisa', to='sbs.HavaLevel'),
        ),
    ]
