# Generated by Django 3.2.6 on 2022-03-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0004_auto_20220311_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='branch',
        ),
    ]
