# Generated by Django 3.2.6 on 2022-03-22 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0006_preregistration_referencecoach_referencereferee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'), ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Kayıt Durumu')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='dekont/', verbose_name='coachApplication ')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RefereeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'), ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Kayıt Durumu')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='dekont/', verbose_name='refereeApplication ')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='coach',
            name='branch',
            field=models.ManyToManyField(to='sbs.Branch'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='grades',
            field=models.ManyToManyField(related_name='Refereegrades', to='sbs.HavaLevel'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='visa',
            field=models.ManyToManyField(related_name='Refereevisa', to='sbs.HavaLevel'),
        ),
        migrations.CreateModel(
            name='VisaSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('location', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'), ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Kayıt Durumu')),
                ('forWhichClazz', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.branch', verbose_name='branş')),
                ('coach', models.ManyToManyField(related_name='coach', to='sbs.Coach')),
                ('coachApplication', models.ManyToManyField(related_name='coachApplication', to='sbs.CoachApplication')),
                ('referee', models.ManyToManyField(related_name='referee', to='sbs.Referee')),
                ('refereeApplication', models.ManyToManyField(related_name='refereeApplication', to='sbs.RefereeApplication')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='refereeapplication',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sbs.referee'),
        ),
        migrations.AddField(
            model_name='coachapplication',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sbs.coach'),
        ),
    ]
